import type {GetStaticProps} from 'next'
import Head from 'next/head'

const Home = ({title}: {title: string}) => {
  return (
    <div className={"container m-auto pl-8 pr-8"}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"container m-auto pl-8 pr-8"}>
        <h1>{title}</h1>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            title: "My blog"
        },
        revalidate: 3600,
    }
}

export default Home
