import type {GetStaticProps} from "next";
import Head from "next/head";
import client from "../contentful/index";
import {IArticle, IArticleFields, IMain, IMainFields} from "../contentful";
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import Link from "next/link";

const Home = ({main, articles}: {main: IMain, articles: IArticle}) => {
  return (
    <div className={"container m-auto px-4"}>
      <Head>
        <title>{main.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"container m-auto px-4"}>
          <div
              className={"overflow-hidden relative"}
              style={{
                  background: `url("http:${main.fields.background?.fields.file.url}") no-repeat center / cover`,
              }}
          >
              <div
                  className={"py-20 flex flex-col items-center justify-center"}
                  style={{
                      backdropFilter: `contrast(.8)`,
                      minHeight: `400px`,
                      height: `50vh`
                  }}
              >
                  <h1 className={"text-center text-white text-4xl uppercase font-bold mb-4"}>{main.fields.title}</h1>

                  <div className={"text-center text-white text-2xl font-medium"}>
                      {documentToReactComponents(main.fields.description!)}
                  </div>
              </div>
          </div>
          <h1 className="text-center text-gray-700 my-12 font-bold text-4xl">Articles</h1>
          <div className="flex flex-wrap -mx-4">
              {articles.map(article => {
                  return (
                      <div key={article.fields.slug} className="w-full max-w-full mb-8 sm:w-1/2 px-4 lg:w-1/3 flex flex-col">
                          <picture>
                              <img src={`https:${article.fields.image?.fields.file.url}`} alt="Card img"
                                   className="object-cover object-center w-full h-48"/>
                          </picture>
                          <div className="flex flex-grow">
                              <div className="triangle"></div>
                              <div className="flex flex-col justify-between px-4 py-6 bg-white border border-gray-400 text">
                                  <div>
                                      <Link href={`/acrticles/${article.fields.slug}`}>
                                          <a href="#" className="block mb-4 text-2xl font-black leading-tight hover:underline hover:text-blue-600">
                                              {article.fields.title}
                                          </a>
                                      </Link>

                                      <p className="mb-4">
                                          {article.fields.description}
                                      </p>
                                  </div>
                                  <div>
                                      <Link href={`/acrticles/${article.fields.slug}`}>
                                          <button className="inline-block pb-1 mt-2 text-base font-black text-blue-600 uppercase border-b border-transparent hover:border-blue-600">
                                              {article.fields.action}
                                          </button>
                                      </Link>
                                  </div>
                              </div>
                          </div>
                      </div>
                  )
              })}
          </div>
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    const main = await client.getEntries<IMainFields>({
        content_type: "main",
        limit: 1,
    });

    const articleEntries = await client.getEntries<IArticleFields>({
        content_type: "article",
        select: "fields.title,fields.slug,fields.description,fields.action,fields.image",
    });

    const [mainPage] = main.items;

    return {
        props: {
            title: "My blog",
            main: mainPage,
            articles: articleEntries.items
        },
        revalidate: 3600,
    }
}

export default Home


